"""add source import audit log

Revision ID: 2dd871292d0a
Revises: 68ed1d36c20d
Create Date: 2026-09-29 16:49:49.452221
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.common


revision: str = '2dd871292d0a'
down_revision: Union[str, None] = '68ed1d36c20d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_import_logs',
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('stored_path', sa.String(length=1000), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('confirmed_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('input_rows', sa.Integer(), nullable=False),
    sa.Column('result_counts', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_import_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_import_logs_sha256'), ['sha256'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('source_import_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_import_logs_sha256'))

    op.drop_table('source_import_logs')
    # ### end Alembic commands ###

