"""initial PublicDB2 core schema

Revision ID: 68ed1d36c20d
Revises: 
Create Date: 2026-09-29 16:13:14.537344
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.common


revision: str = '68ed1d36c20d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('official_name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('agency_type', sa.Enum('CENTRAL_GOVERNMENT', 'AGENCY', 'COMMISSION', 'METROPOLITAN_GOVERNMENT', 'BASIC_LOCAL_GOVERNMENT', 'PUBLIC_INSTITUTION', 'OTHER', name='agencytype', native_enum=False), nullable=False),
    sa.Column('external_identifier', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('homepage_url', sa.String(length=2048), nullable=True),
    sa.Column('parent_agency_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_identifier')
    )
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agencies_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_agencies_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_agencies_parent_agency_id'), ['parent_agency_id'], unique=False)

    op.create_table('change_events',
    sa.Column('entity_type', sa.Enum('AGENCY', 'ORG_UNIT', 'DUTY', 'PERSON', 'PERSON_ASSIGNMENT', 'CONTACT_POINT', 'SOURCE', 'SOURCE_BINDING', name='entitytype', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('ENTITY_ADDED', 'ENTITY_CHANGED', 'ENTITY_MISSING', 'ENTITY_RESTORED', 'CONTACT_CHANGED', 'OTHER', name='changeeventtype', native_enum=False), nullable=False),
    sa.Column('field_name', sa.String(length=200), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('review_status', sa.Enum('PENDING_REVIEW', 'APPROVED', 'REJECTED', 'IGNORED', name='reviewstatus', native_enum=False), nullable=False),
    sa.Column('detected_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', app.models.common.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.create_index('ix_change_events_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_events_review_status'), ['review_status'], unique=False)

    op.create_table('sources',
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('normalized_url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.Enum('STAFF_DIRECTORY', 'ORG_CHART', 'DEPARTMENT_PAGE', 'OFFICIAL_API', 'PUBLIC_DATA', 'GENERAL_PAGE', 'DOCUMENT', 'OTHER', name='sourcetype', native_enum=False), nullable=False),
    sa.Column('collection_method', sa.Enum('API', 'WEB_PAGE', 'WEB_CRAWL', 'FILE', 'DOCUMENT', name='collectionmethod', native_enum=False), nullable=False),
    sa.Column('data_format', sa.Enum('HTML', 'JSON', 'XML', 'CSV', 'XLSX', 'PDF', 'TEXT', 'UNKNOWN', name='dataformat', native_enum=False), nullable=False),
    sa.Column('last_checked_at', app.models.common.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', app.models.common.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_url')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_active'), ['active'], unique=False)

    op.create_table('crawl_runs',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', name='runstatus', native_enum=False), nullable=False),
    sa.Column('connection_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'SKIPPED', name='stagestatus', native_enum=False), nullable=False),
    sa.Column('raw_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'SKIPPED', name='stagestatus', native_enum=False), nullable=False),
    sa.Column('extraction_status', sa.Enum('PENDING', 'SUCCESS', 'FAILED', 'SKIPPED', name='stagestatus', native_enum=False), nullable=False),
    sa.Column('started_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', app.models.common.UTCDateTime(timezone=True), nullable=True),
    sa.Column('records_observed', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_runs_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_runs_status'), ['status'], unique=False)

    op.create_table('org_units',
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('parent_org_unit_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('normalized_name', sa.String(length=300), nullable=False),
    sa.Column('unit_type', sa.Enum('OFFICE', 'BUREAU', 'DEPARTMENT', 'DIVISION', 'TEAM', 'CENTER', 'BRANCH', 'OTHER', name='orgunittype', native_enum=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['parent_org_unit_id'], ['org_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('org_units', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_org_units_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_units_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_units_normalized_name'), ['normalized_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_org_units_parent_org_unit_id'), ['parent_org_unit_id'], unique=False)

    op.create_table('people',
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('normalized_name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_people_normalized_name'), ['normalized_name'], unique=False)

    op.create_table('duties',
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('org_unit_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duties_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_duties_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duties_org_unit_id'), ['org_unit_id'], unique=False)

    op.create_table('observations',
    sa.Column('crawl_run_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('observed_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('page_url', sa.String(length=2048), nullable=False),
    sa.Column('artifact_path', sa.String(length=1024), nullable=True),
    sa.Column('artifact_sha256', sa.String(length=64), nullable=True),
    sa.Column('raw_text_excerpt', sa.Text(), nullable=True),
    sa.Column('structured_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['crawl_run_id'], ['crawl_runs.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_observations_crawl_run_id'), ['crawl_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_observations_source_id'), ['source_id'], unique=False)

    op.create_table('person_assignments',
    sa.Column('person_id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('org_unit_id', sa.Uuid(), nullable=True),
    sa.Column('position_title', sa.String(length=300), nullable=False),
    sa.Column('role_description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_units.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('person_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_person_assignments_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_assignments_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_assignments_org_unit_id'), ['org_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_person_assignments_person_id'), ['person_id'], unique=False)

    op.create_table('source_bindings',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('org_unit_id', sa.Uuid(), nullable=True),
    sa.Column('scope_key', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('excluded_at', app.models.common.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_units.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'scope_key', name='uq_source_binding_scope')
    )
    with op.batch_alter_table('source_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_source_bindings_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_bindings_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_bindings_org_unit_id'), ['org_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_bindings_source_id'), ['source_id'], unique=False)

    op.create_table('change_detections',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'PARTIAL', 'FAILED', name='runstatus', native_enum=False), nullable=False),
    sa.Column('candidates_found', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('started_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('finished_at', app.models.common.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_detections_observation_id'), ['observation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_change_detections_source_id'), ['source_id'], unique=False)

    op.create_table('contact_points',
    sa.Column('agency_id', sa.Uuid(), nullable=False),
    sa.Column('org_unit_id', sa.Uuid(), nullable=True),
    sa.Column('person_assignment_id', sa.Uuid(), nullable=True),
    sa.Column('duty_id', sa.Uuid(), nullable=True),
    sa.Column('contact_type', sa.Enum('PHONE', 'EMAIL', 'FAX', 'WEB_FORM', 'URL', 'ADDRESS', 'OTHER', name='contacttype', native_enum=False), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.Column('normalized_value', sa.String(length=2048), nullable=False),
    sa.Column('purpose_text', sa.Text(), nullable=True),
    sa.Column('verified_at', app.models.common.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['duty_id'], ['duties.id'], ),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_units.id'], ),
    sa.ForeignKeyConstraint(['person_assignment_id'], ['person_assignments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_points', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_points_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_points_agency_id'), ['agency_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_points_contact_type'), ['contact_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_points_duty_id'), ['duty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_points_normalized_value'), ['normalized_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_points_org_unit_id'), ['org_unit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_points_person_assignment_id'), ['person_assignment_id'], unique=False)

    op.create_table('source_occurrences',
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('AGENCY', 'ORG_UNIT', 'DUTY', 'PERSON', 'PERSON_ASSIGNMENT', 'CONTACT_POINT', 'SOURCE', 'SOURCE_BINDING', name='entitytype', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=200), nullable=True),
    sa.Column('observed_value', sa.Text(), nullable=True),
    sa.Column('context_text', sa.Text(), nullable=True),
    sa.Column('source_locator', sa.String(length=1000), nullable=True),
    sa.Column('observed_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('source_occurrences', schema=None) as batch_op:
        batch_op.create_index('ix_source_occurrences_entity', ['entity_type', 'entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_occurrences_observation_id'), ['observation_id'], unique=False)

    op.create_table('contact_history',
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.String(length=2048), nullable=False),
    sa.Column('normalized_value', sa.String(length=2048), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('valid_from', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('valid_to', app.models.common.UTCDateTime(timezone=True), nullable=True),
    sa.Column('change_event_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', app.models.common.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['change_event_id'], ['change_events.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contact_points.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_history_change_event_id'), ['change_event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contact_history_contact_id'), ['contact_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_history_contact_id'))
        batch_op.drop_index(batch_op.f('ix_contact_history_change_event_id'))

    op.drop_table('contact_history')
    with op.batch_alter_table('source_occurrences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_occurrences_observation_id'))
        batch_op.drop_index('ix_source_occurrences_entity')

    op.drop_table('source_occurrences')
    with op.batch_alter_table('contact_points', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_points_person_assignment_id'))
        batch_op.drop_index(batch_op.f('ix_contact_points_org_unit_id'))
        batch_op.drop_index(batch_op.f('ix_contact_points_normalized_value'))
        batch_op.drop_index(batch_op.f('ix_contact_points_duty_id'))
        batch_op.drop_index(batch_op.f('ix_contact_points_contact_type'))
        batch_op.drop_index(batch_op.f('ix_contact_points_agency_id'))
        batch_op.drop_index(batch_op.f('ix_contact_points_active'))

    op.drop_table('contact_points')
    with op.batch_alter_table('change_detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_detections_source_id'))
        batch_op.drop_index(batch_op.f('ix_change_detections_observation_id'))

    op.drop_table('change_detections')
    with op.batch_alter_table('source_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_bindings_source_id'))
        batch_op.drop_index(batch_op.f('ix_source_bindings_org_unit_id'))
        batch_op.drop_index(batch_op.f('ix_source_bindings_agency_id'))
        batch_op.drop_index(batch_op.f('ix_source_bindings_active'))

    op.drop_table('source_bindings')
    with op.batch_alter_table('person_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_person_assignments_person_id'))
        batch_op.drop_index(batch_op.f('ix_person_assignments_org_unit_id'))
        batch_op.drop_index(batch_op.f('ix_person_assignments_agency_id'))
        batch_op.drop_index(batch_op.f('ix_person_assignments_active'))

    op.drop_table('person_assignments')
    with op.batch_alter_table('observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_observations_source_id'))
        batch_op.drop_index(batch_op.f('ix_observations_crawl_run_id'))

    op.drop_table('observations')
    with op.batch_alter_table('duties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duties_org_unit_id'))
        batch_op.drop_index(batch_op.f('ix_duties_agency_id'))
        batch_op.drop_index(batch_op.f('ix_duties_active'))

    op.drop_table('duties')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_people_agency_id'))
        batch_op.drop_index(batch_op.f('ix_people_active'))

    op.drop_table('people')
    with op.batch_alter_table('org_units', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_org_units_parent_org_unit_id'))
        batch_op.drop_index(batch_op.f('ix_org_units_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_org_units_agency_id'))
        batch_op.drop_index(batch_op.f('ix_org_units_active'))

    op.drop_table('org_units')
    with op.batch_alter_table('crawl_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_runs_status'))
        batch_op.drop_index(batch_op.f('ix_crawl_runs_source_id'))

    op.drop_table('crawl_runs')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_active'))

    op.drop_table('sources')
    with op.batch_alter_table('change_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_events_review_status'))
        batch_op.drop_index('ix_change_events_entity')

    op.drop_table('change_events')
    with op.batch_alter_table('agencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agencies_parent_agency_id'))
        batch_op.drop_index(batch_op.f('ix_agencies_normalized_name'))
        batch_op.drop_index(batch_op.f('ix_agencies_active'))

    op.drop_table('agencies')
    # ### end Alembic commands ###

